package setting;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class Setting {

	public static void main(String[] args) {
		new Setting();
	}

	private String URL = "jdbc:mysql://localhost/?" + "CharacterEncoding=UTF-8&" + "serverTimezone=UTC&"
			+ "allowPublicKeyRetrieval=true&" + "allowLoadLocalInfile=true&" + "allowMultiQueries=true";
	private String USER = "root";
	private String PW = "1234";
	private Connection con;
	private PreparedStatement pstmt;

	public Setting() {
		try {
			con = DriverManager.getConnection(URL, USER, PW);
			System.out.println("연결 성공");
		} catch (SQLException e) {
			e.printStackTrace();
		}
		setDb("-- MySQL Script generated by MySQL Workbench\r\n" + "-- Mon Jan  9 19:25:15 2023\r\n"
				+ "-- Model: New Model    Version: 1.0\r\n" + "-- MySQL Workbench Forward Engineering\r\n" + "\r\n"
				+ "SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\r\n"
				+ "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\r\n"
				+ "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';\r\n"
				+ "\r\n" + "-- -----------------------------------------------------\r\n" + "-- Schema sa_project\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "DROP SCHEMA IF EXISTS `sa_project` ;\r\n" + "\r\n"
				+ "-- -----------------------------------------------------\r\n" + "-- Schema sa_project\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "CREATE SCHEMA IF NOT EXISTS `sa_project` DEFAULT CHARACTER SET utf8 ;\r\n" + "USE `sa_project` ;\r\n"
				+ "\r\n" + "-- -----------------------------------------------------\r\n"
				+ "-- Table `sa_project`.`user`\r\n" + "-- -----------------------------------------------------\r\n"
				+ "CREATE TABLE IF NOT EXISTS `sa_project`.`user` (\r\n"
				+ "  `u_no` INT(11) NOT NULL AUTO_INCREMENT,\r\n" + "  `u_id` VARCHAR(10) NULL,\r\n"
				+ "  `u_name` VARCHAR(10) NULL,\r\n" + "  `u_pw` VARCHAR(10) NULL,\r\n" + "  PRIMARY KEY (`u_no`))\r\n"
				+ "ENGINE = InnoDB;\r\n" + "\r\n" + "\r\n"
				+ "-- -----------------------------------------------------\r\n" + "-- Table `sa_project`.`notice`\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "CREATE TABLE IF NOT EXISTS `sa_project`.`notice` (\r\n"
				+ "  `n_no` INT(11) NOT NULL AUTO_INCREMENT,\r\n" + "  `u_no` INT(11) NULL,\r\n"
				+ "  `n_title` VARCHAR(50) NULL,\r\n" + "  `n_contents` VARCHAR(150) NULL,\r\n"
				+ "  PRIMARY KEY (`n_no`),\r\n" + "  INDEX `fk_notice_user_idx` (`u_no` ASC) VISIBLE,\r\n"
				+ "  CONSTRAINT `fk_notice_user`\r\n" + "    FOREIGN KEY (`u_no`)\r\n"
				+ "    REFERENCES `sa_project`.`user` (`u_no`)\r\n" + "    ON DELETE NO ACTION\r\n"
				+ "    ON UPDATE NO ACTION)\r\n" + "ENGINE = InnoDB;\r\n" + "\r\n" + "\r\n"
				+ "SET SQL_MODE=@OLD_SQL_MODE;\r\n" + "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\r\n"
				+ "SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;");
	}

	public int setDb(String sql, Object... values) {
		try {
			pstmt = con.prepareStatement(sql);

			int cnt = 1;

			for (Object value : values) {
				pstmt.setObject(cnt++, value);
			}

			System.out.println("setDb 성공");

			return pstmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
			System.out.println("setDb 실패");
			return -1;
		}
	}

}
